package com.qf.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

@Table(name = "carpic")
@Entity
public class CarPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpic.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpic.pic1
     *
     * @mbg.generated
     */
    private String pic1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpic.pic2
     *
     * @mbg.generated
     */
    private String pic2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpic.pic3
     *
     * @mbg.generated
     */
    private String pic3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpic
     *
     * @mbg.generated
     */
    public CarPic(Integer cid, String pic1, String pic2, String pic3) {
        this.cid = cid;
        this.pic1 = pic1;
        this.pic2 = pic2;
        this.pic3 = pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpic
     *
     * @mbg.generated
     */
    public CarPic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpic.cid
     *
     * @return the value of carpic.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpic.cid
     *
     * @param cid the value for carpic.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpic.pic1
     *
     * @return the value of carpic.pic1
     *
     * @mbg.generated
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpic.pic1
     *
     * @param pic1 the value for carpic.pic1
     *
     * @mbg.generated
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpic.pic2
     *
     * @return the value of carpic.pic2
     *
     * @mbg.generated
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpic.pic2
     *
     * @param pic2 the value for carpic.pic2
     *
     * @mbg.generated
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpic.pic3
     *
     * @return the value of carpic.pic3
     *
     * @mbg.generated
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpic.pic3
     *
     * @param pic3 the value for carpic.pic3
     *
     * @mbg.generated
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }
}