package com.qf.domain;

import javax.persistence.*;

@Table(name = "code")
@Entity
public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.codeid
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer codeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated
     */
    public Code(Integer codeid, String email, String code) {
        this.codeid = codeid;
        this.email = email;
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated
     */
    public Code() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.codeid
     *
     * @return the value of code.codeid
     *
     * @mbg.generated
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.codeid
     *
     * @param codeid the value for code.codeid
     *
     * @mbg.generated
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.email
     *
     * @return the value of code.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.email
     *
     * @param email the value for code.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code
     *
     * @return the value of code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code
     *
     * @param code the value for code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}