package com.qf.domain;

import lombok.Data;

import javax.persistence.*;

@Entity
@Table(name = "seller")
@Data
public class Seller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sid
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.provice
     *
     * @mbg.generated
     */
    private String provice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.Idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.email
     *
     * @mbg.generated
     */
    private String email;

    private String code;
    //判断是否卖家，卖家为1，买家为0
    private Integer ifseller;
    //判断是否支付，已支付为1，后台改权限，待定
    private Integer ifpay;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated
     */

}