package com.qf.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "seller_car")
public class SellerCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_car.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_car.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_car
     *
     * @mbg.generated
     */
    public SellerCar(Integer sid, Integer cid) {
        this.sid = sid;
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_car
     *
     * @mbg.generated
     */
    public SellerCar() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_car.sid
     *
     * @return the value of seller_car.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_car.sid
     *
     * @param sid the value for seller_car.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_car.cid
     *
     * @return the value of seller_car.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_car.cid
     *
     * @param cid the value for seller_car.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}