package com.qf.dao;

import com.qf.domain.CarPic;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CarPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpic
     *
     * @mbg.generated
     */
    int insert(CarPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpic
     *
     * @mbg.generated
     */
    int insertSelective(CarPic record);
    List getPics(Integer cid);
}